CREATE TABLE DBSCHEMAVERSION (
VERSIONNUMBER		TEXT	PRIMARY KEY 	NOT NULL,
VERSIONAPPLICATION	TEXT			NOT NULL,
VERSIONDATE		TEXT			NOT NULL,
VERSIONINFOURL		TEXT,		
VERSIONID		INT
);	

CREATE TABLE DYNAHERD	(
HERDID			INT	PRIMARY KEY 	NOT NULL,
PRODUCTIONTYPEID	INT			NOT NULL,
LATITUDE		REAL			NOT NULL,
LONGITUDE		REAL			NOT NULL,
INITIALSTATECODE	TEXT			NOT NULL,
DAYSININITIALSTATE	INT			NOT NULL,
DAYSLEFTININITIALSTATE	INT			NOT NULL,
INITIALSIZE		INT 			NOT NULL,
FINALSTATECODE	T	EXT,	
FINALCONTROLSTATECODE	TEXT,	
FINALDETECTIONSTATECODE	TEXT,	
CUMULINFECTED		INT ,		
CUMULDETECTED		INT ,		
CUMULDESTROYED		INT ,		
CUMULVACCINATED		INT 
);		


CREATE TABLE DYNABLOB	(
DYNBLOBID		TEXT 	PRIMARY KEY 	NOT NULL,
ZONEPERIMETERS		TEXT
);

CREATE TABLE READALLCODES (
CODEID			INT	PRIMARY KEY 	NOT NULL,
CODE			TEXT			NOT NULL,
CODETYPE		TEXT			NOT NULL,
CODEDESCRIPTION		TEXT			NOT NULL
);

CREATE TABLE READALLCODETYPES	(
CODETYPEID	INT	PRIMARY KEY 	NOT NULL,
CODETYPE	TEXT			NOT NULL,
CODEDESCRIPTION	TEXT			NOT NULL
);

----CONSTRAIN THIS?

CREATE TABLE INCHART (
CHARTID		INT		PRIMARY KEY 	NOT NULL,
FIELDNAME	TEXT,	
CHARTNAME	TEXT				NOT NULL,
ISPDF		INT				NOT NULL,
CHARTTYPE	TEXT,		
MEAN		REAL,		
STDDEV		REAL,		
MIN		REAL,		
MODE		REAL,		
MAX		REAL,		
ALPHA		REAL,		
ALPHA2		REAL,		
BETA		REAL,		
LOCATION	REAL,		
SCALE		REAL,		
SHAPE		REAL,		
N		INT,		
P		REAL,		
M		INT,		
D		INT,		
DMIN		INT,		
DMAX		INT,		
THETA		REAL,		
A		REAL,		
S		INT,		
XAXISUNITS	TEXT,	
YAXISUNITS	TEXT,	
NOTES		TEXT
);


CREATE TABLE INCHARTDETAIL (
CHARTID		INT		NOT NULL, -- DISCUSS pk NEEDED HERE
POINTORDER	INT		NOT NULL,
X		REAL		NOT NULL,
Y		REAL		NOT NULL
);

CREATE TABLE INCONTROLSGLOBAL 	(
CONTROLSGLOBALID		TEXT		NOT NULL, -- USES THAT TEXT pk
INCLUDEDETECTION		INT		NOT NULL DEFAULT 0,
INCLUDETRACING			INT		NOT NULL DEFAULT 0,
INCLUDETRACINGHERDEXAM		INT		NOT NULL DEFAULT 0,
INCLUDETRACINGTESTING		INT		NOT NULL DEFAULT 0,
INCLUDEDESTRUCTION		INT		NOT NULL DEFAULT 0,
DESTRPROGRAMDELAY		INT,		
DESTRCAPACITYRELID		INT,		
DESTRPRIORITYORDER		TEXT,		
DESTRREASONORDER		TEXT,		
INCLUDEVACCINATION		INT		NOT NULL DEFAULT 0,
VACCDETECTEDUNITSBEFORESTART	INT,		
VACCCAPACITYRELID		INT,		
VACCPRIORITYORDER		TEXT,		
INCLUDEZONES			INT		NOT NULL DEFAULT 0,
VACCRETROSPECTIVEDAYS		INT,		
VACCCAPACITYSTARTRELID		INT,		
VACCCAPACITYRESTARTRELID	INT
);	

CREATE TABLE INCUSTOMOUTPUTDEFINITIONS (
DEFID			INT	PRIMARY KEY 	NOT NULL,
OUTPUTNAME		TEXT			NOT NULL,
OUTPUTTYPECODE		TEXT,	
OUTPUTFREQUENCYCODE	TEXT,	
SQL			TEXT	
);


CREATE TABLE INDISEASESPREAD (
PRODUCTIONTYPEPAIRID		INT	PRIMARY KEY 	NOT NULL,
SPREADMETHODCODE		TEXT,
LATENTCANINFECT			INT,
SUBCLINICALCANINFECT		INT,
MEANCONTACTRATE			REAL,
USEFIXEDCONTACTRATE		INT,
FIXEDCONTACTRATE		REAL,
INFECTIONPROBABILITY		REAL,
DISTANCEPDFID			INT,
MOVEMENTCONTROLRELID		INT,
TRANSPORTDELAYPDFID		INT,
PROBAIRBORNESPREAD1KM		REAL,
MAXDISTAIRBORNESPREAD		REAL,
WINDDIRECTIONSTART		INT,
WINDDIRECTIONEND		INT
);


CREATE TABLE	INGENERAL (
INGENERALID			TEXT,  ----pk
LANGUAGE			TEXT,
SCENARIODESCR			TEXT,
ITERATIONS			INT,
DAYS				INT,
SIMSTOPREASON			TEXT,
INCLUDECONTACTSPREAD		INT,
INCLUDEAIRBORNESPREAD		INT,
USEAIRBORNEEXPONENTIALDECAY	INT,
USEWITHINHERDPREVALENCE		INT,
COSTTRACKDESTRUCTION		INT,
COSTTRACKVACCINATION		INT,
COSTTRACKZONESURVEILLANCE	INT,
USEFIXEDRANDOMSEED		INT,
RANDOMSEED			INT,
SAVEALLDAILYOUTPUTS		INT,
SAVEDAILYOUTPUTSFORITERATIONS	INT,
WRITEDAILYSTATESFILE		INT,
DAILYSTATESFILENAME		TEXT,
SAVEDAILYEVENTS			INT,
SAVEDAILYEXPOSURES		INT,
SAVEITERATIONOUTPUTSFORHERDS	INT,
USECUSTOMOUTPUTS		INT,
WRITENAADSMAPOUTPUT		INT,
NAADSMAPDIRECTORY		TEXT
);


CREATE TABLE INPRODUCTIONTYPE (
PRODUCTIONTYPEID			INT 	PRIMARY KEY 	NOT NULL,
PRODTYPEDESCR				TEXT			NOT NULL,
USEDISEASETRANSITION			INT,
DISLATENTPERIODPDFID			INT,
DISSUBCLINICALPERIODPDFID		INT,
DISCLINICALPERIODPDFID			INT,
DISIMMUNEPERIODPDFID			INT,
DISPREVALENCERELID			INT,
USEDETECTION				INT,
DETPROBOBSVSTIMECLINICALRELID		INT,
DETPROBREPORTVSFIRSTDETECTIONRELID	INT,
TRACEDIRECTFORWARD			INT,
TRACEDIRECTBACK				INT,
TRACEDIRECTSUCCESS			REAL,
TRACEDIRECTTRACEPERIOD			INT,
TRACEINDIRECTFORWARD			INT,
TRACEINDIRECTBACK			INT,
TRACEINDIRECTSUCCESS			REAL,
TRACEINDIRECTTRACEPERIOD		INT,
TRACEDELAYPDFID				INT,
USEBASICDESTRUCTION			INT,
DESTRISRINGTRIGGER			INT,
DESTRRINGRADIUS				REAL,
DESTRISRINGTARGET			INT,
DESTRDIRECTFORWARDTRACES		INT,
DESTRINDIRECTFORWARDTRACES		INT,
DESTRDIRECTBACKTRACES			INT,
DESTRINDIRECTBACKTRACES			INT,
DESTRPRIORITY				INT,
USEVACCINATION				INT,
VACCMINTIMEBETWEENVACCINATIONS		INT,
VACCVACCINATEDETECTED			INT,
VACCDAYSTOIMMUNITY			INT,
VACCIMMUNEPERIODPDFID			INT,
VACCRING				INT,
VACCRINGRADIUS				REAL,
VACCPRIORITY				INT,
COSTDESTRAPPRAISALPERUNIT		REAL,
COSTDESTRCLEANINGPERUNIT		REAL,
COSTDESTREUTHANASIAPERANIMAL		REAL,
COSTDESTRINDEMNIFICATIONPERANIMAL	REAL,
COSTDESTRDISPOSALPERANIMAL		REAL,
COSTVACCSETUPPERUNIT			REAL,
COSTVACCTHRESHOLD			INT,
COSTVACCBASELINEPERANIMAL		REAL,
COSTVACCADDITIONALPERANIMAL		REAL,
ZONEDETECTIONISTRIGGER			INT,
ZONEDIRECTTRACEISTRIGGER		INT,
ZONEINDIRECTTRACEISTRIGGER		INT,
EXAMDIRECTFORWARD			INT,
EXAMDIRECTFORWARDMULTIPLIER		REAL,
EXAMINDIRECTFORWARD			INT,
EXAMINDIRECTFORWARDMULTIPLIER		REAL,
EXAMDIRECTBACK				INT,
EXAMDIRECTBACKMULTIPLIER		REAL,
EXAMINDIRECTBACK			INT,
EXAMINDIRECTBACKMULTIPLIER		REAL,
TESTDIRECTFORWARD			INT,
TESTINDIRECTFORWARD			INT,
TESTDIRECTBACK				INT,
TESTINDIRECTBACK			INT,
TESTSPECIFICITY				REAL,
TESTSENSITIVITY				REAL,
TESTDELAYPDFID				INT,
VACCRESTROSPECTIVEDAYS			INT
);

CREATE TABLE INPRODUCTIONTYPEPAIR (

PRODUCTIONTYPEPAIRID	INT		INT 	PRIMARY KEY 	NOT NULL,
SOURCEPRODUCTIONTYPEID	INT		NOT NULL,
DESTPRODUCTIONTYPEID	INT		NOT NULL,
USEDIRECTCONTACT	INT		NOT NULL DEFAULT 0,
DIRECTCONTACTSPREADID	INT,		
USEINDIRECTCONTACT	INT		NOT NULL DEFAULT 0,
INDIRECTCONTACTSPREADID	INT,		
USEAIRBORNESPREAD	INT		NOT NULL DEFAULT 0,
AIRBORNECONTACTSPREADID	INT		
);


CREATE TABLE INZONE (
ZONEID		INT		PRIMARY KEY 	NOT NULL,
ZONEDESCRIPTION	TEXT		NOT NULL,
ZONERADIUS	REAL		NOT NULL
);

CREATE TABLE INZONEPRODUCTIONTYPEPAIR (
INZONEPRODUCTIONTYPEPAIRID	INT	PRIMARY KEY 	NOT NULL,
ZONEID				INT			NOT NULL,
PRODUCTIONTYPEID		INT			NOT NULL,
USEDIRECTMOVEMENTCONTROL	INT			NOT NULL DEFAULT 0,
ZONEDIRECTMOVEMENTRELID		INT,		
USEINDIRECTMOVEMENTCONTROL	INT			NOT NULL DEFAULT 0,
ZONEINDIRECTMOVEMENTRELID	INT,		
USEDETECTIONMULTIPLIER		INT			NOT NULL DEFAULT 0,
ZONEDETECTIONMULTIPLIER		REAL,		
COSTSURVPERANIMALDAY		REAL	
); 	

-- conceptually, if you are making this group, you should know all data
CREATE TABLE INGROUP (

GROUPID			INT	PRIMARY KEY 	NOT NULL,
SUBGROUPID		INT			NOT NULL,
GROUPPRODUCTIONTYPES	TEXT			NOT NULL  -- check how this looks
);

CREATE TABLE INTRIGGER (
TRIGGERID		INT	PRIMARY KEY 	NOT NULL,
TRIGGERCODE		INT			NOT NULL,
TRIGGERDAYS		INT
TRIGGERRATE		INT  	-- not sure on this datatype
TRIGGERPRODUCTIONTYPES	TEXT  -- check how this looks
);
-----------------------------------------
-- outputs
-- not going to constrain outputs at all
-----------------------------------------

CREATE TABLE OUTDAILYBYPRODUCTIONTYPE (
ITERATION		INT,
PRODUCTIONTYPEID	INT,
DAY			INT,
TSDUSUSC		INT,
TSDASUSC		INT,
TSDULAT			INT,
TSDALAT			INT,
TSDUSUBC		INT,
TSDASUBC		INT,
TSDUCLIN		INT,
TSDACLIN		INT,
TSDUNIMM		INT,
TSDANIMM		INT,
TSDUVIMM		INT,
TSDAVIMM		INT,
TSDUDEST		INT,
TSDADEST		INT,
TSCUSUSC		INT,
TSCASUSC		INT,
TSCULAT			INT,
TSCALAT			INT,
TSCUSUBC		INT,
TSCASUBC		INT,
TSCUCLIN		INT,
TSCACLIN		INT,
TSCUNIMM		INT,
TSCANIMM		INT,
TSCUVIMM		INT,
TSCAVIMM		INT,
TSCUDEST		INT,
TSCADEST		INT,
INFNUAIR		INT,
INFNAAIR		INT,
INFNUDIR		INT,
INFNADIR		INT,
INFNUIND		INT,
INFNAIND		INT,
INFCUINI		INT,
INFCAINI		INT,
INFCUAIR		INT,
INFCAAIR		INT,
INFCUDIR		INT,
INFCADIR		INT,
INFCUIND		INT,
INFCAIND		INT,
EXPCUDIR		INT,
EXPCADIR		INT,
EXPCUIND		INT,
EXPCAIND		INT,
TRCUDIRFWD		INT,
TRCADIRFWD		INT,
TRCUINDFWD		INT,
TRCAINDFWD		INT,
TRCUDIRPFWD		INT,
TRCADIRPFWD		INT,
TRCUINDPFWD		INT,
TRCAINDPFWD		INT,
TOCUDIRFWD		INT,
TOCUINDFWD		INT,
TOCUDIRBACK		INT,
TOCUINDBACK		INT,
TRNUDIRFWD		INT,
TRNADIRFWD		INT,
TRNUINDFWD		INT,
TRNAINDFWD		INT,
TRCUDIRBACK		INT,
TRCADIRBACK		INT,
TRCUINDBACK		INT,
TRCAINDBACK		INT,
TRCUDIRPBACK		INT,
TRCADIRPBACK		INT,
TRCUINDPBACK		INT,
TRCAINDPBACK		INT,
TRNUDIRBACK		INT,
TRNADIRBACK		INT,
TRNUINDBACK		INT,
TRNAINDBACK		INT,
TONUDIRFWD		INT,
TONUINDFWD		INT,
TONUDIRBACK		INT,
TONUINDBACK		INT,
EXMCUDIRFWD		INT,
EXMCADIRFWD		INT,
EXMCUINDFWD		INT,
EXMCAINDFWD		INT,
EXMCUDIRBACK		INT,
EXMCADIRBACK		INT,
EXMCUINDBACK		INT,
EXMCAINDBACK		INT,
EXMNUALL		INT,
EXMNAALL		INT,
TSTCUDIRFWD		INT,
TSTCADIRFWD		INT,
TSTCUINDFWD		INT,
TSTCAINDFWD		INT,
TSTCUDIRBACK		INT,
TSTCADIRBACK		INT,
TSTCUINDBACK		INT,
TSTCAINDBACK		INT,
TSTCUTRUEPOS		INT,
TSTCATRUEPOS		INT,
TSTNUTRUEPOS		INT,
TSTNATRUEPOS		INT,
TSTCUTRUENEG		INT,
TSTCATRUENEG		INT,
TSTNUTRUENEG		INT,
TSTNATRUENEG		INT,
TSTCUFALSEPOS		INT,
TSTCAFALSEPOS		INT,
TSTNUFALSEPOS		INT,
TSTNAFALSEPOS		INT,
TSTCUFALSENEG		INT,
TSTCAFALSENEG		INT,
TSTNUFALSENEG		INT,
TSTNAFALSENEG		INT,
DETNUCLIN		INT,
DETNACLIN		INT,
DETCUCLIN		INT,
DETCACLIN		INT,
DETNUTEST		INT,
DETNATEST		INT,
DETCUTEST		INT,
DETCATEST		INT,
DESCUINI		INT,
DESCAINI		INT,
DESCUDET		INT,
DESCADET		INT,
DESCUDIRFWD		INT,
DESCADIRFWD		INT,
DESCUINDFWD		INT,
DESCAINDFWD		INT,
DESCUDIRBACK		INT,
DESCADIRBACK		INT,
DESCUINDBACK		INT,
DESCAINDBACK		INT,
DESCURING		INT,
DESCARING		INT,
DESNUALL		INT,
DESNAALL		INT,
DESWUALL		INT,
DESWAALL		INT,
VACCUINI		INT,
VACCAINI		INT,
VACCURING		INT,
VACCARING		INT,
VACNUALL		INT,
VACNAALL		INT,
VACWUALL		INT,
VACWAALL		INT,
ZONNFOCI		INT,
ZONCFOCI		INT,
APPDUINFECTIOUS		INT
);

CREATE TABLE OUTDAILYBYZONE (
ITERATION	INT,
DAY		INT,
ZONEID		INT,
ZONEAREA	REAL,
ZONEPERIMETER	REAL
);

CREATE TABLE OUTDAILYBYZONEANDPRODUCTIONTYPE  (
ITERATION		INT,
DAY			INT,
ZONEID			INT,
PRODUCTIONTYPEID	INT,
UNITDAYSINZONE		INT,
ANIMALDAYSINZONE	INT,
UNITSINZONE		INT,
ANIMALSINZONE		INT
);

CREATE TABLE OUTDAILYEVENTS (

ITERATION	INT,
DAY		INT,
EVENT		INT,
HERDID		INT,
ZONEID		INT,
EVENTCODE	TEXT,
NEWSTATECODE	TEXT,
TESTRESULTCODE	TEXT
);

CREATE TABLE OUTDAILYEXPOSURES (
ITERATION		INT,
DAY			INT,
EXPOSURE		INT,
INITIATEDDAY		INT,
EXPOSEDHERDID		INT,
EXPOSEDZONEID		INT,
EXPOSINGHERDID		INT,
EXPOSINGZONEID		INT,
SPREADMETHODCODE	TEXT,
ISADEQUATE		INT,
EXPOSINGHERDSTATUSCODE	TEXT,
EXPOSEDHERDSTATUSCODE	TEXT
);

CREATE TABLE OUTEPIDEMICCURVES (
ITERATION		INT,
DAY			INT,
PRODUCTIONTYPEID	INT,
INFECTEDUNITS		INT,
INFECTEDANIMALS		INT,
DETECTEDUNITS		INT,
DETECTEDANIMALS		INT,
INFECTIOUSUNITS		INT,
APPARENTINFECTIOUSUNITS	INT
);

CREATE TABLE OUTGENERAL (
OUTGENERALID		TEXT, -- yuck is this that versionapplication thing
SIMULATIONSTARTTIME	TEXT,
SIMULATIONENDTIME	TEXT,
COMPLETEDITERATIONS	INT,
VERSION			TEXT
);

CREATE TABLE OUTITERATION (
ITERATION	INT,
DISEASEENDED	INT,
DISEASEENDDAY	INT,
OUTBREAKENDED	INT,
OUTBREAKENDDAY	INT,
ZONEFOCICREATED	INT,
DESWUMAX	INT,
DESWUMAXDAY	INT,
DESWAMAX	REAL,
DESWAMAXDAY	INT,
DESWUTIMEMAX	INT,
DESWUTIMEAVG	REAL,
VACWUMAX	INT,
VACWUMAXDAY	INT,
VACWAMAX	REAL,
VACWAMAXDAY	INT,
VACWUTIMEMAX	INT,
VACWUTIMEAVG	REAL
);


CREATE TABLE OUTITERATIONBYHERD (
ITERATION		INT,
HERDID			INT,
LASTSTATUSCODE		TEXT,
LASTSTATUSDAY		INT,
LASTCONTROLSTATECODE	TEXT,
LASTCONTROLSTATEDAY	INT
);



CREATE TABLE OUTITERATIONBYPRODUCTIONTYPE (

ITERATION		INT,
PRODUCTIONTYPEID	INT,
TSCUSUSC		INT,
TSCASUSC		INT,
TSCULAT			INT,
TSCALAT			INT,
TSCUSUBC		INT,
TSCASUBC		INT,
TSCUCLIN		INT,
TSCACLIN		INT,
TSCUNIMM		INT,
TSCANIMM		INT,
TSCUVIMM		INT,
TSCAVIMM		INT,
TSCUDEST		INT,
TSCADEST		INT,
INFCUINI		INT,
INFCAINI		INT,
INFCUAIR		INT,
INFCAAIR		INT,
INFCUDIR		INT,
INFCADIR		INT,
INFCUIND		INT,
INFCAIND		INT,
EXPCUDIR		INT,
EXPCADIR		INT,
EXPCUIND		INT,
EXPCAIND		INT,
TRCUDIRFWD		INT,
TRCADIRFWD		INT,
TRCUINDFWD		INT,
TRCAINDFWD		INT,
TRCUDIRPFWD		INT,
TRCADIRPFWD		INT,
TRCUINDPFWD		INT,
TRCAINDPFWD		INT,
TRCUDIRBACK		INT,
TRCADIRBACK		INT,
TRCUINDBACK		INT,
TRCAINDBACK		INT,
TRCUDIRPBACK		INT,
TRCADIRPBACK		INT,
TRCUINDPBACK		INT,
TRCAINDPBACK		INT,
TOCUDIRFWD		INT,
TOCUINDFWD		INT,
TOCUDIRBACK		INT,
TOCUINDBACK		INT,
EXMCUDIRFWD		INT,
EXMCADIRFWD		INT,
EXMCUINDFWD		INT,
EXMCAINDFWD		INT,
EXMCUDIRBACK		INT,
EXMCADIRBACK		INT,
EXMCUINDBACK		INT,
EXMCAINDBACK		INT,
TSTCUDIRFWD		INT,
TSTCADIRFWD		INT,
TSTCUINDFWD		INT,
TSTCAINDFWD		INT,
TSTCUDIRBACK		INT,
TSTCADIRBACK		INT,
TSTCUINDBACK		INT,
TSTCAINDBACK		INT,
TSTCUTRUEPOS		INT,
TSTCATRUEPOS		INT,
TSTCUTRUENEG		INT,
TSTCATRUENEG		INT,
TSTCUFALSEPOS		INT,
TSTCAFALSEPOS		INT,
TSTCUFALSENEG		INT,
TSTCAFALSENEG		INT,
DETCUCLIN		INT,
DETCACLIN		INT,
DETCUTEST		INT,
DETCATEST		INT,
DESCUINI		INT,
DESCAINI		INT,
DESCUDET		INT,
DESCADET		INT,
DESCUDIRFWD		INT,
DESCADIRFWD		INT,
DESCUINDFWD		INT,
DESCAINDFWD		INT,
DESCUDIRBACK		INT,
DESCADIRBACK		INT,
DESCUINDBACK		INT,
DESCAINDBACK		INT,
DESCURING		INT,
DESCARING		INT,
DESWUMAX		INT,
DESWAMAX		REAL
DESWUMAXDAY		INT,
DESWAMAXDAY		INT,
DESWUTIMEMAX		INT,
DESWUTIMEAVG		REAL
DESWUDAYSINQUEUE	REAL
DESWADAYSINQUEUE	REAL
VACCUINI		INT,
VACCAINI		INT,
VACCURING		INT,
VACCARING		INT,
VACWUMAX		INT,
VACWAMAX		REAL
VACWUMAXDAY		INT,
VACWAMAXDAY		INT,
VACWUTIMEMAX		REAL
VACWUTIMEAVG		INT,
ZONCFOCI		INT,
FIRSTDETECTION		INT,
FIRSTDETUINF		INT,
FIRSTDETAINF		INT,
FIRSTDESTRUCTION	INT,
FIRSTVACCINATION	INT,
LASTDETECTION		INT
);

CREATE TABLE OUTITERATIONBYZONE (
ITERATION		INT,
ZONEID			INT,
MAXZONEAREA		REAL,
MAXZONEAREADAY		INT,
FINALZONEAREA		REAL,
MAXZONEPERIMETER	REAL,
MAXZONEPERIMETERDAY	INT,
FINALZONEPERIMETER	REAL
);

CREATE TABLE OUTITERATIONBYZONEANDPRODUCTIONTYPE (
ITERATION		INT,
ZONEID			INT,
PRODUCTIONTYPEID	INT,
UNITDAYSINZONE		INT,
ANIMALDAYSINZONE	INT,
COSTSURVEILLANCE	REAL
);

CREATE TABLE OUTITERATIONCOSTS (
ITERATION		INT,
PRODUCTIONTYPEID	INT,
DESTRAPPRAISAL		REAL,
DESTRCLEANING		REAL,
DESTREUTHANASIA		REAL,
DESTRINDEMNIFICATION	REAL,
DESTRDISPOSAL		REAL,
VACCSETUP		REAL,
VACCVACCINATION		REAL
);






