------------------------------------------------------------------
-- Input Tables
-- Schoenbaum
-- 2/19/14 - scripted for Django
--
-- Note:  any RELID or PDFID will not display with a label.
--          RELID's and PDFID are displayed in the function form
----------------------------------------------------------------

CREATE TABLE DBSCHEMAVERSION (
VERSION_NUMBER		TEXT	PRIMARY KEY 	NOT NULL,
VERSION_APPLICATION	TEXT			NOT NULL,
VERSION_DATE		TEXT			NOT NULL,
VERSION_INFO_URL	TEXT,		
VERSION_ID		INT
);	

CREATE TABLE DYNAHERD	(
HERD_ID			INT	PRIMARY KEY 	NOT NULL,
PRODUCTIONTYPEID	INT			NOT NULL,
LATITUDE		REAL			NOT NULL,
LONGITUDE		REAL			NOT NULL,
INITIAL_STATE_CODE	TEXT			NOT NULL,
DAYS_IN_INITIAL_STATE	INT			NOT NULL,
DAYS_LEFT_IN_INITIAL_STATE	INT			NOT NULL,
INITIAL_SIZE		INT 			NOT NULL,
FINAL_STATE_CODE		TEXT,	
FINAL_CONTROL_STATE_CODE	TEXT,	
FINAL_DETECTION_STATE_CODE	TEXT,	
CUM_INFECTED		INT ,		
CUM_DETECTED		INT ,		
CUM_DESTROYED		INT ,		
CUM_VACCINATED		INT 
);		


CREATE TABLE DYNABLOB	(
DYNBLOB_ID		TEXT 	PRIMARY KEY 	NOT NULL,
ZONE_PERIMETERS		TEXT
);

CREATE TABLE READALLCODES (
CODE_ID			INT	PRIMARY KEY 	NOT NULL,
CODE			TEXT			NOT NULL,
CODE_TYPE		TEXT			NOT NULL,
CODE_DESCRIPTION		TEXT			NOT NULL
);

CREATE TABLE READALLCODETYPES	(
CODE_TYPE_ID		INT	PRIMARY KEY 	NOT NULL,
CODE_TYPE		TEXT			NOT NULL,
CODE_DESCRIPTION	TEXT			NOT NULL
);

----CONSTRAIN THIS?
---- MS 2/19 NAMES NOT MODIFIED DO NOT DISPLAY ON FORM
CREATE TABLE INCHART (
CHARTID		INT		PRIMARY KEY 	NOT NULL,
FIELDNAME	TEXT,	
CHART_NAME	TEXT				NOT NULL,
ISPDF		INT				NOT NULL,
CHART_TYPE	TEXT,		
MEAN		REAL,		
STD_DEV		REAL,		
MIN		REAL,		
MODE		REAL,		
MAX		REAL,		
ALPHA		REAL,		
ALPHA2		REAL,		
BETA		REAL,		
LOCATION	REAL,		
SCALE		REAL,		
SHAPE		REAL,		
N		INT,		
P		REAL,		
M		INT,		
D		INT,		
DMIN		INT,		
DMAX		INT,		
THETA		REAL,		
A		REAL,		
S		INT,		
X_AXIS_UNITS	TEXT,	
Y_AXIS_UNITS	TEXT,	
NOTES		TEXT
);


CREATE TABLE INCHARTDETAIL (
CHARTID		INT		NOT NULL, -- DISCUSS pk NEEDED HERE
POINTORDER	INT		NOT NULL,
X		REAL		NOT NULL,
Y		REAL		NOT NULL
);

CREATE TABLE INCONTROLSGLOBAL 	(
CONTROLSGLOBALID		TEXT		NOT NULL, -- USES THAT TEXT pk
INCLUDE_DETECTION		INT		NOT NULL DEFAULT 0,
INCLUDE_TRACING			INT		NOT NULL DEFAULT 0,
INCLUDE_TRACING_HERD_EXAM		INT		NOT NULL DEFAULT 0,
INCLUDE_TRACING_TESTING		INT		NOT NULL DEFAULT 0,
INCLUDE_DESTRUCTION		INT		NOT NULL DEFAULT 0,
DESTRUCTION_DELAY		INT,		
DESTRCAPACITYRELID		INT,		
DESTRUCTION_PRIORITY_ORDER			TEXT,		
DESTRUCION_REASON_ORDER				TEXT,		
INCLUDE_VACCINATION				INT		NOT NULL DEFAULT 0,
VACCINCATION_DETECTED_UNITS_BEFORE_START	INT,		
VACCCAPACITYRELID				INT,		
VACCINATION_PRIORITY_ORDER			TEXT,		
INCLUDE_ZONES					INT		NOT NULL DEFAULT 0,
VACCINATION_RETROSPECTIVE_DAYS			INT,		
VACCCAPACITYSTARTRELID		INT,		
VACCCAPACITYRESTARTRELID	INT
);	

-- CUSTOM OUTPUTS REMOVED

CREATE TABLE INDISEASESPREAD (
PRODUCTIONTYPEPAIRID		INT	PRIMARY KEY 	NOT NULL,
SPREADMETHODCODE		TEXT,
LATENT_CAN_INFECT			INT,
SUBCLINICAL_CAN_INFECT		INT,
MEAN_CONTACT_RATE			REAL,
USE_FIXED_CONTACT_RATE		INT,
FIXED_CONTACT_RATE		REAL,
INFECTION_PROBABILITY		REAL,
DISTANCEPDFID			INT,
MOVEMENTCONTROLRELID		INT,
TRANSPORTDELAYPDFID		INT,
PROBAIRBORNESPREAD1KM		REAL,
MAXDISTAIRBORNESPREAD		REAL,
WIND_DIRECTION_START		INT,
WIND_DIRECTION_END		INT
);


CREATE TABLE	INGENERAL (
INGENERALID			TEXT,  ----pk
LANGUAGE			TEXT,
SCENARIO_DESCRIPTION			TEXT,
ITERATIONS			INT,
DAYS				INT,
SIMSTOPREASON			TEXT,
INCLUDECONTACTSPREAD		INT,  -- THESE PRESENT IN A RADIO BUTTON NOW
INCLUDEAIRBORNESPREAD		INT,
USE_AIRBORNE_EXPONENTIAL_DECAY	INT,
USE_WITHIN_HERD_PREVALENCE		INT,
COST_TRACK_DESTRUCTION		INT,
COST_TRACK_VACCINATION		INT,
COST_TRACK_ZONE_SURVEILLANCE	INT,
USE_FIXED_RANDOM_SEED		INT,
RANDOMSEED			INT,
SAVE_ALL_DAILY_OUTPUTS		INT,
SAVE_DAILY_OUTPUTS_FOR_ITERATIONS	INT,
WRITE_DAILY_STATES_FILE		INT,
DAILY_STATES_FILENAME		TEXT,
SAVE_DAILY_EVENTS			INT,
SAVE_DAILY_EXPOSURES		INT,
SAVE_ITERATION_OUTPUTS_FOR_HERDS	INT,
--USECUSTOMOUTPUTS		INT,  NO CUSTOM OUTPUTS
WRITE_MAP_OUTPUT		INT,
MAP_DIRECTORY		TEXT
);


CREATE TABLE INPRODUCTIONTYPE (
PRODUCTION_TYPE_ID			INT 	PRIMARY KEY 	NOT NULL,
PRODUCTION_TYPE_NAME				TEXT			NOT NULL,
USE_DISEASE_TRANSITION			INT,
DISLATENTPERIODPDFID			INT,
DISSUBCLINICALPERIODPDFID		INT,
DISCLINICALPERIODPDFID			INT,
DISIMMUNEPERIODPDFID			INT,
DISPREVALENCERELID			INT,
USE_DETECTION				INT,
DETPROBOBSVSTIMECLINICALRELID		INT,
DETPROBREPORTVSFIRSTDETECTIONRELID	INT,
TRACE_DIRECT_FORWARD			INT,
TRACE_DIRECT_BACK				INT,
TRACE_DIRECT_SUCCESS			REAL,
TRACE_DIRECT_TRACE_PERIOD			INT,
TRACE_INDIRECT_FORWARD			INT,
TRACE_INDIRECT_BACK			INT,
TRACE_INDIRECT_SUCCESS			REAL,
TRACE_INDIRECT_TRACE_PERIOD		INT,
TRACEDELAYPDFID				INT,
USE_DESTRUCTION			INT,
DESTRUCTION_IS_RING_TRIGGER			INT,
DESTRUCTION_RING_RADIUS				REAL,
DESTRUCTION_IS_RING_TARGET			INT,
DESTROY_DIRECT_FORWARD_TRACES		INT,
DESTROY_INDIRECT_FORWARD_TRACES		INT,
DESTROY_DIRECT_BACK_TRACES			INT,
DESTROY_INDIRECT_BACK_TRACES			INT,
DESTRUCTION_PRIORITY				INT,
USE_VACCINATION				INT,
VACC_MIN_TIME_BETWEEN_VACCINATIONS		INT,
VACC_VACCINATE_DETECTED			INT,
VACC_DAYS_TO_IMMUNITY			INT,
VACCIMMUNEPERIODPDFID			INT,
VACC_RING				INT,
VACC_RING_RADIUS				REAL,
VACC_PRIORITY				INT,
COST_DESTR_APPRAISAL_PER_UNIT		REAL,
COST_DESTR_CLEANING_PER_UNIT		REAL,
COST_DESTR_EUTHANASIA_PER_ANIMAL		REAL,
COST_DESTR_INDEMNIFICATION_PER_ANIMAL	REAL,
COST_DESTR_DISPOSAL_PER_ANIMAL		REAL,
COST_VACC_SETUP_PER_UNIT			REAL,
COST_VACC_THRESHOLD			INT,
COST_VACC_BASELINE_PER_ANIMAL		REAL,
COST_VACC_ADDITIONAL_PER_ANIMAL		REAL,
ZONE_DETECTION_IS_TRIGGER			INT,
ZONE_DIRECT_TRACE_IS_TRIGGER		INT,
ZONE_INDIRECT_TRACE_IS_TRIGGER		INT,
EXAM_DIRECT_FORWARD			INT,
EXAM_DIRECT_FORWARD_MULTIPLIER		REAL,
EXAM_INDIRECT_FORWARD			INT,
EXAM_INDIRECT_FORWARD_MULTIPLIER		REAL,
EXAM_DIREC_TBACK				INT,
EXAM_DIRECT_BACK_MULTIPLIER		REAL,
EXAM_INDIRECT_BACK			INT,
EXAM_INDIRECT_BACK_MULTIPLIER		REAL,
TEST_DIRECT_FORWARD			INT,
TEST_INDIRECT_FORWARD			INT,
TEST_DIRECT_BACK				INT,
TEST_INDIRECT_BACK			INT,
TEST_SPECIFICITY				REAL,
TEST_SENSITIVITY				REAL,
TESTDELAYPDFID				INT,
VACC_RESTROSPECTIVE_DAYS			INT
);

CREATE TABLE INPRODUCTIONTYPEPAIR (

PRODUCTIONTYPEPAIRID	INT		INT 	PRIMARY KEY 	NOT NULL,
SOURCEPRODUCTIONTYPEID	INT		NOT NULL,
DESTPRODUCTIONTYPEID	INT		NOT NULL,
USE_DIRECT_CONTACT	INT		NOT NULL DEFAULT 0,
DIRECTCONTACTSPREADID	INT,		
USE_INDIRECT_CONTACT	INT		NOT NULL DEFAULT 0,
INDIRECTCONTACTSPREADID	INT,		
USE_AIRBORNE_SPREAD	INT		NOT NULL DEFAULT 0,
AIRBORNECONTACTSPREADID	INT		
);


CREATE TABLE INZONE (
ZONEID		INT		PRIMARY KEY 	NOT NULL,
ZONE_DESCRIPTION	TEXT		NOT NULL,
ZONE_RADIUS	REAL		NOT NULL
);

CREATE TABLE INZONEPRODUCTIONTYPEPAIR (
INZONEPRODUCTIONTYPEPAIRID	INT	PRIMARY KEY 	NOT NULL,
ZONEID				INT			NOT NULL,
PRODUCTIONTYPEID		INT			NOT NULL,
USE_DIRECTMOVEMENT_CONTROL	INT			NOT NULL DEFAULT 0,
ZONEDIRECTMOVEMENTRELID		INT,		
USE_INDIRECT_MOVEMENT_CONTROL	INT			NOT NULL DEFAULT 0,
ZONEINDIRECTMOVEMENTRELID	INT,		
USE_DETECTION_MULTIPLIER		INT			NOT NULL DEFAULT 0,
ZONE_DETECTION_MULTIPLIER		REAL,		
COST_SURV_PER_ANIMAL_DAY		REAL	
); 	

-- conceptually, if you are making this group, you should know all data
CREATE TABLE INGROUP (
-- THIS IS v3.3
GROUPID			INT	PRIMARY KEY 	NOT NULL,
SUBGROUPID		INT			NOT NULL,
GROUPPRODUCTIONTYPES	TEXT			NOT NULL  -- check how this looks
);

CREATE TABLE INTRIGGER (
TRIGGERID		INT	PRIMARY KEY 	NOT NULL,
TRIGGERCODE		INT			NOT NULL,
TRIGGER_DAYS		INT
TRIGGER_RATE		INT  	-- not sure on this datatype
TRIGGERPRODUCTIONTYPES	TEXT  -- check how this looks
);
-----------------------------------------
-- outputs
-- not going to constrain outputs at all
-----------------------------------------

CREATE TABLE OUTDAILYBYPRODUCTIONTYPE (
ITERATION		INT,
PRODUCTIONTYPEID	INT,
DAY			INT,
TSDUSUSC		INT,
TSDASUSC		INT,
TSDULAT			INT,
TSDALAT			INT,
TSDUSUBC		INT,
TSDASUBC		INT,
TSDUCLIN		INT,
TSDACLIN		INT,
TSDUNIMM		INT,
TSDANIMM		INT,
TSDUVIMM		INT,
TSDAVIMM		INT,
TSDUDEST		INT,
TSDADEST		INT,
TSCUSUSC		INT,
TSCASUSC		INT,
TSCULAT			INT,
TSCALAT			INT,
TSCUSUBC		INT,
TSCASUBC		INT,
TSCUCLIN		INT,
TSCACLIN		INT,
TSCUNIMM		INT,
TSCANIMM		INT,
TSCUVIMM		INT,
TSCAVIMM		INT,
TSCUDEST		INT,
TSCADEST		INT,
INFNUAIR		INT,
INFNAAIR		INT,
INFNUDIR		INT,
INFNADIR		INT,
INFNUIND		INT,
INFNAIND		INT,
INFCUINI		INT,
INFCAINI		INT,
INFCUAIR		INT,
INFCAAIR		INT,
INFCUDIR		INT,
INFCADIR		INT,
INFCUIND		INT,
INFCAIND		INT,
EXPCUDIR		INT,
EXPCADIR		INT,
EXPCUIND		INT,
EXPCAIND		INT,
TRCUDIRFWD		INT,
TRCADIRFWD		INT,
TRCUINDFWD		INT,
TRCAINDFWD		INT,
TRCUDIRPFWD		INT,
TRCADIRPFWD		INT,
TRCUINDPFWD		INT,
TRCAINDPFWD		INT,
TOCUDIRFWD		INT,
TOCUINDFWD		INT,
TOCUDIRBACK		INT,
TOCUINDBACK		INT,
TRNUDIRFWD		INT,
TRNADIRFWD		INT,
TRNUINDFWD		INT,
TRNAINDFWD		INT,
TRCUDIRBACK		INT,
TRCADIRBACK		INT,
TRCUINDBACK		INT,
TRCAINDBACK		INT,
TRCUDIRPBACK		INT,
TRCADIRPBACK		INT,
TRCUINDPBACK		INT,
TRCAINDPBACK		INT,
TRNUDIRBACK		INT,
TRNADIRBACK		INT,
TRNUINDBACK		INT,
TRNAINDBACK		INT,
TONUDIRFWD		INT,
TONUINDFWD		INT,
TONUDIRBACK		INT,
TONUINDBACK		INT,
EXMCUDIRFWD		INT,
EXMCADIRFWD		INT,
EXMCUINDFWD		INT,
EXMCAINDFWD		INT,
EXMCUDIRBACK		INT,
EXMCADIRBACK		INT,
EXMCUINDBACK		INT,
EXMCAINDBACK		INT,
EXMNUALL		INT,
EXMNAALL		INT,
TSTCUDIRFWD		INT,
TSTCADIRFWD		INT,
TSTCUINDFWD		INT,
TSTCAINDFWD		INT,
TSTCUDIRBACK		INT,
TSTCADIRBACK		INT,
TSTCUINDBACK		INT,
TSTCAINDBACK		INT,
TSTCUTRUEPOS		INT,
TSTCATRUEPOS		INT,
TSTNUTRUEPOS		INT,
TSTNATRUEPOS		INT,
TSTCUTRUENEG		INT,
TSTCATRUENEG		INT,
TSTNUTRUENEG		INT,
TSTNATRUENEG		INT,
TSTCUFALSEPOS		INT,
TSTCAFALSEPOS		INT,
TSTNUFALSEPOS		INT,
TSTNAFALSEPOS		INT,
TSTCUFALSENEG		INT,
TSTCAFALSENEG		INT,
TSTNUFALSENEG		INT,
TSTNAFALSENEG		INT,
DETNUCLIN		INT,
DETNACLIN		INT,
DETCUCLIN		INT,
DETCACLIN		INT,
DETNUTEST		INT,
DETNATEST		INT,
DETCUTEST		INT,
DETCATEST		INT,
DESCUINI		INT,
DESCAINI		INT,
DESCUDET		INT,
DESCADET		INT,
DESCUDIRFWD		INT,
DESCADIRFWD		INT,
DESCUINDFWD		INT,
DESCAINDFWD		INT,
DESCUDIRBACK		INT,
DESCADIRBACK		INT,
DESCUINDBACK		INT,
DESCAINDBACK		INT,
DESCURING		INT,
DESCARING		INT,
DESNUALL		INT,
DESNAALL		INT,
DESWUALL		INT,
DESWAALL		INT,
VACCUINI		INT,
VACCAINI		INT,
VACCURING		INT,
VACCARING		INT,
VACNUALL		INT,
VACNAALL		INT,
VACWUALL		INT,
VACWAALL		INT,
ZONNFOCI		INT,
ZONCFOCI		INT,
APPDUINFECTIOUS		INT
);

CREATE TABLE OUTDAILYBYZONE (
ITERATION	INT,
DAY		INT,
ZONEID		INT,
ZONEAREA	REAL,
ZONEPERIMETER	REAL
);

CREATE TABLE OUTDAILYBYZONEANDPRODUCTIONTYPE  (
ITERATION		INT,
DAY			INT,
ZONEID			INT,
PRODUCTIONTYPEID	INT,
UNITDAYSINZONE		INT,
ANIMALDAYSINZONE	INT,
UNITSINZONE		INT,
ANIMALSINZONE		INT
);

CREATE TABLE OUTDAILYEVENTS (

ITERATION	INT,
DAY		INT,
EVENT		INT,
HERDID		INT,
ZONEID		INT,
EVENTCODE	TEXT,
NEWSTATECODE	TEXT,
TESTRESULTCODE	TEXT
);

CREATE TABLE OUTDAILYEXPOSURES (
ITERATION		INT,
DAY			INT,
EXPOSURE		INT,
INITIATEDDAY		INT,
EXPOSEDHERDID		INT,
EXPOSEDZONEID		INT,
EXPOSINGHERDID		INT,
EXPOSINGZONEID		INT,
SPREADMETHODCODE	TEXT,
ISADEQUATE		INT,
EXPOSINGHERDSTATUSCODE	TEXT,
EXPOSEDHERDSTATUSCODE	TEXT
);

CREATE TABLE OUTEPIDEMICCURVES (
ITERATION		INT,
DAY			INT,
PRODUCTIONTYPEID	INT,
INFECTEDUNITS		INT,
INFECTEDANIMALS		INT,
DETECTEDUNITS		INT,
DETECTEDANIMALS		INT,
INFECTIOUSUNITS		INT,
APPARENTINFECTIOUSUNITS	INT
);

CREATE TABLE OUTGENERAL (
OUTGENERALID		TEXT, -- yuck is this that versionapplication thing
SIMULATIONSTARTTIME	TEXT,
SIMULATIONENDTIME	TEXT,
COMPLETEDITERATIONS	INT,
VERSION			TEXT
);

CREATE TABLE OUTITERATION (
ITERATION	INT,
DISEASEENDED	INT,
DISEASEENDDAY	INT,
OUTBREAKENDED	INT,
OUTBREAKENDDAY	INT,
ZONEFOCICREATED	INT,
DESWUMAX	INT,
DESWUMAXDAY	INT,
DESWAMAX	REAL,
DESWAMAXDAY	INT,
DESWUTIMEMAX	INT,
DESWUTIMEAVG	REAL,
VACWUMAX	INT,
VACWUMAXDAY	INT,
VACWAMAX	REAL,
VACWAMAXDAY	INT,
VACWUTIMEMAX	INT,
VACWUTIMEAVG	REAL
);


CREATE TABLE OUTITERATIONBYHERD (
ITERATION		INT,
HERDID			INT,
LASTSTATUSCODE		TEXT,
LASTSTATUSDAY		INT,
LASTCONTROLSTATECODE	TEXT,
LASTCONTROLSTATEDAY	INT
);



CREATE TABLE OUTITERATIONBYPRODUCTIONTYPE (

ITERATION		INT,
PRODUCTIONTYPEID	INT,
TSCUSUSC		INT,
TSCASUSC		INT,
TSCULAT			INT,
TSCALAT			INT,
TSCUSUBC		INT,
TSCASUBC		INT,
TSCUCLIN		INT,
TSCACLIN		INT,
TSCUNIMM		INT,
TSCANIMM		INT,
TSCUVIMM		INT,
TSCAVIMM		INT,
TSCUDEST		INT,
TSCADEST		INT,
INFCUINI		INT,
INFCAINI		INT,
INFCUAIR		INT,
INFCAAIR		INT,
INFCUDIR		INT,
INFCADIR		INT,
INFCUIND		INT,
INFCAIND		INT,
EXPCUDIR		INT,
EXPCADIR		INT,
EXPCUIND		INT,
EXPCAIND		INT,
TRCUDIRFWD		INT,
TRCADIRFWD		INT,
TRCUINDFWD		INT,
TRCAINDFWD		INT,
TRCUDIRPFWD		INT,
TRCADIRPFWD		INT,
TRCUINDPFWD		INT,
TRCAINDPFWD		INT,
TRCUDIRBACK		INT,
TRCADIRBACK		INT,
TRCUINDBACK		INT,
TRCAINDBACK		INT,
TRCUDIRPBACK		INT,
TRCADIRPBACK		INT,
TRCUINDPBACK		INT,
TRCAINDPBACK		INT,
TOCUDIRFWD		INT,
TOCUINDFWD		INT,
TOCUDIRBACK		INT,
TOCUINDBACK		INT,
EXMCUDIRFWD		INT,
EXMCADIRFWD		INT,
EXMCUINDFWD		INT,
EXMCAINDFWD		INT,
EXMCUDIRBACK		INT,
EXMCADIRBACK		INT,
EXMCUINDBACK		INT,
EXMCAINDBACK		INT,
TSTCUDIRFWD		INT,
TSTCADIRFWD		INT,
TSTCUINDFWD		INT,
TSTCAINDFWD		INT,
TSTCUDIRBACK		INT,
TSTCADIRBACK		INT,
TSTCUINDBACK		INT,
TSTCAINDBACK		INT,
TSTCUTRUEPOS		INT,
TSTCATRUEPOS		INT,
TSTCUTRUENEG		INT,
TSTCATRUENEG		INT,
TSTCUFALSEPOS		INT,
TSTCAFALSEPOS		INT,
TSTCUFALSENEG		INT,
TSTCAFALSENEG		INT,
DETCUCLIN		INT,
DETCACLIN		INT,
DETCUTEST		INT,
DETCATEST		INT,
DESCUINI		INT,
DESCAINI		INT,
DESCUDET		INT,
DESCADET		INT,
DESCUDIRFWD		INT,
DESCADIRFWD		INT,
DESCUINDFWD		INT,
DESCAINDFWD		INT,
DESCUDIRBACK		INT,
DESCADIRBACK		INT,
DESCUINDBACK		INT,
DESCAINDBACK		INT,
DESCURING		INT,
DESCARING		INT,
DESWUMAX		INT,
DESWAMAX		REAL
DESWUMAXDAY		INT,
DESWAMAXDAY		INT,
DESWUTIMEMAX		INT,
DESWUTIMEAVG		REAL
DESWUDAYSINQUEUE	REAL
DESWADAYSINQUEUE	REAL
VACCUINI		INT,
VACCAINI		INT,
VACCURING		INT,
VACCARING		INT,
VACWUMAX		INT,
VACWAMAX		REAL
VACWUMAXDAY		INT,
VACWAMAXDAY		INT,
VACWUTIMEMAX		REAL
VACWUTIMEAVG		INT,
ZONCFOCI		INT,
FIRSTDETECTION		INT,
FIRSTDETUINF		INT,
FIRSTDETAINF		INT,
FIRSTDESTRUCTION	INT,
FIRSTVACCINATION	INT,
LASTDETECTION		INT
);

CREATE TABLE OUTITERATIONBYZONE (
ITERATION		INT,
ZONEID			INT,
MAXZONEAREA		REAL,
MAXZONEAREADAY		INT,
FINALZONEAREA		REAL,
MAXZONEPERIMETER	REAL,
MAXZONEPERIMETERDAY	INT,
FINALZONEPERIMETER	REAL
);

CREATE TABLE OUTITERATIONBYZONEANDPRODUCTIONTYPE (
ITERATION		INT,
ZONEID			INT,
PRODUCTIONTYPEID	INT,
UNITDAYSINZONE		INT,
ANIMALDAYSINZONE	INT,
COSTSURVEILLANCE	REAL
);

CREATE TABLE OUTITERATIONCOSTS (
ITERATION		INT,
PRODUCTIONTYPEID	INT,
DESTRAPPRAISAL		REAL,
DESTRCLEANING		REAL,
DESTREUTHANASIA		REAL,
DESTRINDEMNIFICATION	REAL,
DESTRDISPOSAL		REAL,
VACCSETUP		REAL,
VACCVACCINATION		REAL
);
