
from django.forms import Form, FilePathField

class ImportForm(Form):
    parameters_xml = FilePathField(required=True, 
                                   help_text='An XML parameters file generated by the legacy NAADSM program from File > Export Scenario...')
    population_xml = FilePathField(required=True, 
                                   help_text='The population XML to match the parameters file.  This population should contain Production Types '
                                             'that match the names in the scenario file.')
        