set timeout 3
#
# expectations that clean up in case of error. Note that `$test' is
# a purely local variable.
#
# The first of these is used to match any bad responses, and resynchronise
# things by finding a prompt. The second is a timeout error, and shouldn't
# ever be triggered.
#
expect_after {
	-re "\[^\n\r\]*$prompt$" {
		fail "$test (bad match)"
		if { $verbose > 0 } {
			regexp ".*\r\n(\[^\r\n\]+)(\[\r\n\])+$prompt$" \
						$expect_out(buffer) "" output
			send_user "\tUnmatched output: \"$output\"\n"
		}
	}
	timeout {
		fail "$test (timeout)"
	}
}

#
# Test that the progression of an infection works correctly.
#
set test "infect_1"
send "reset\n"
expect {
	-re "$prompt$" { }
}
send "unit (\"beef\",1,0,0)\n"
expect {
	-re "$prompt$" { }
}
send "infect (0,1,2,3,2)\n"
expect {
	-re "$prompt$" { }
}
set error [progression_test [list \
  "Lat" \
  "Subc" \
  "Subc" \
  "Clin" \
  "Clin" \
  "Clin" \
  "NImm" \
  "NImm" \
  "Susc" \
  "Susc" \
  "Susc"]]
if { [string compare $error ""] == 0 } {
	pass "$test"
} else {
	fail "$test $error"
}

#
# Test the progression when one or more stages takes 0 days.
#
set test "infect_with_skipped_states_1"
send "reset\n"
expect {
	-re "$prompt$" { }
}
send "unit (\"beef\",1,0,0)\n"
expect {
	-re "$prompt$" { }
}
send "infect (0,1,0,3,2)\n"
expect {
	-re "$prompt$" { }
}
set error [progression_test [list \
  "Lat" \
  "Clin" \
  "Clin" \
  "Clin" \
  "NImm" \
  "NImm" \
  "Susc" \
  "Susc" \
  "Susc"]]
if { [string compare $error ""] == 0 } {
	pass "$test"
} else {
	fail "$test $error"
}

#
# Test that you cannot infect a dead unit.
#
set test "infect_dead_unit"
send "reset\n"
expect {
	-re "$prompt$" { }
}
send "unit (\"beef\",1,0,0)\n"
expect {
	-re "$prompt$" { }
}
send "destroy (0)\n"
expect {
	-re "$prompt$" { }
}
set error [progression_test [list "Dest"]]
if { [string compare $error ""] == 0 } {
	send "infect (0,2,0,1,1)\n"
	expect {
		-re "$prompt$" { }
	}
	set error [progression_test [list "Dest" "Dest" "Dest" "Dest" "Dest"]]
}
if { [string compare $error ""] == 0 } {
	pass "$test"
} else {
	fail "$test $error"
}

#
# Test that you cannot infect an immune unit.
#
set test "infect_immune_unit_1"
send "reset\n"
expect {
	-re "$prompt$" { }
}
send "unit (\"beef\",1,0,0)\n"
expect {
	-re "$prompt$" { }
}
send "infect (0,1,0,1,2)\n"
expect {
	-re "$prompt$" { }
}
set error [progression_test [list "Lat" "Clin" "NImm"]]
if { [string compare $error ""] == 0 } {
	send "infect (0,2,0,1,1)\n"
	expect {
		-re "$prompt$" { }
	}
	set error [progression_test [list "NImm" "Susc" "Susc" "Susc" "Susc" "Susc"]]
}
if { [string compare $error ""] == 0 } {
	pass "$test"
} else {
	fail "$test $error"
}

set test "infect_immune_unit_2"
send "reset\n"
expect {
	-re "$prompt$" { }
}
send "unit (\"beef\",1,0,0)\n"
expect {
	-re "$prompt$" { }
}
send "vaccinate (0,0,2)\n"
expect {
	-re "$prompt$" { }
}
set error [progression_test [list "VImm"]]
if { [string compare $error ""] == 0 } {
	send "infect (0,2,0,1,1)\n"
	expect {
		-re "$prompt$" { }
	}
	set error [progression_test [list "VImm" "Susc" "Susc" "Susc" "Susc" "Susc"]]
}
if { [string compare $error ""] == 0 } {
	pass "$test"
} else {
	fail "$test $error"
}

#
# Test that you cannot double-infect a unit.
#
set test "infect_infected_unit_1"
send "reset\n"
expect {
	-re "$prompt$" { }
}
send "unit (\"beef\",1,0,0)\n"
expect {
	-re "$prompt$" { }
}
send "infect (0,2,0,1,1)\n"
expect {
	-re "$prompt$" { }
}
set error [progression_test [list "Lat"]]
if { [string compare $error ""] == 0 } {
	send "infect (0,4,0,1,1)\n"
	expect {
		-re "$prompt$" { }
	}
	set error [progression_test [list "Lat" "Clin" "NImm" "Susc" "Susc" "Susc" "Susc" "Susc"]]
}
if { [string compare $error ""] == 0 } {
	pass "$test"
} else {
	fail "$test $error"
}
