-----------------------------------------
-- outputs
-- not going to constrain outputs at all
-- Schoenbaum
-- 2/24/14 - base script
-----------------------------------------

CREATE TABLE OUTDAILYBYPRODUCTIONTYPE (
ITERATION		INT,
_PRODUCTIONTYPEID	INT,
DAY			INT,
TRANSITION_STATE_DAILY_UNIT_SUSCEPTIBLE		INT,
TRANSITION_STATE_DAILY_ANIMAL_SUSCEPTIBLE	INT,
TRANSITION_STATE_DAILY_UNIT_LATENT		INT,
TRANSITION_STATE_DAILY_ANIMAL_LATENT		INT,
TRANSITION_STATE_DAILY_UNIT_SUBCLINICAL		INT,
TRANSITION_STATE_DAILY_ANIMAL_SUBCLINICAL	INT,
TRANSITION_STATE_DAILY_UNIT_CLINICAL		INT,
TRANSITION_STATE_DAILY_ANIMAL_CLINICAL		INT,
TRANSITION_STATE_DAILY_UNIT_NAT_IMMUNE		INT,
TRANSITION_STATE_DAILY_ANIMAL_NAT_IMMUNE	INT,
TRANSITION_STATE_DAILY_UNIT_VAC_IMMUNE		INT,
TRANSITION_STATE_DAILY_ANIMAL_VAC_IMMUNE	INT,
TRANSITION_STATE_DAILY_UNIT_DESTROYED		INT,
TRANSITION_STATE_DAILY_ANIMAL_DESTROYED		INT,
TRANSITION_STATE_CUM_UNIT_SUSCEPTIBLE		INT,
TRANSITION_STATE_CUM_ANIMAL_SUSCEPTIBLE		INT,
TRANSITION_STATE_CUM_UNIT_LATENT		INT,
TRANSITION_STATE_CUM_ANIMAL_LATENT		INT,
TRANSITION_STATE_CUM_UNIT_SUBCLINICAL		INT,
TRANSITION_STATE_CUM_ANIMAL_SUBCLINICAL		INT,
TRANSITION_STATE_CUM_UNIT_CLINICAL		INT,
TRANSITION_STATE_CUM_ANIMAL_CLINICAL		INT,
TRANSITION_STATE_CUM_UNIT_NAT_IMMUNE		INT,
TRANSITION_STATE_CUM_ANIMAL_NAT_IMMUNE		INT,
TRANSITION_STATE_CUM_UNIT_VAC_IMMUNE		INT,
TRANSITION_STATE_CUM_ANIMAL_VAC_IMMUNE		INT,
TRANSITION_STATE_CUM_UNIT_DESTROYED		INT,
TRANSITION_STATE_CUM_ANIMAL_DESTROYED		INT,
INFECTION_NEW_UNIT_AIR		INT, -- INFNU in XML SPEC  HOWEVER IS RECOMBINED WITH CONTACT METHOD FOR OUTPUT FIELD
INFECTION_NEW_ANIMAL_AIR	INT, -- INFNA in XML SPEC
INFECTION_NEW_UNIT_DIR		INT,
INFECTION_NEW_ANIMAL_DIR	INT,
INFECTION_NEW_UNIT_IND		INT,
INFECTION_NEW_ANIMAL_IND	INT,
INFECTION_CUM_UNIT_INITIAL	INT, -- INFCU in XML SPEC
INFECTION_CUM_ANIMAL_INITIAL	INT,
INFECTION_CUM_UNIT_AIR		INT, -- INFCU in XML SPEC
INFECTION_CUM_ANIMAL_AIR	INT,
INFECTION_CUM_UNIT_DIR		INT,
INFECTION_CUM_ANIMAL_DIR	INT,
INFECTION_CUM_UNIT_IND		INT,
INFECTION_CUM_ANIMAL_IND	INT,
EXPOSED_CUM_UNIT_DIR		INT,
EXPOSED_CUM_ANIMAL_DIR		INT,
EXPOSED_CUM_UNIT_IND		INT,
EXPOSED_CUM_ANIMAL_IND		INT,
TRACE_CUM_UNIT_DIR_FWD		INT,
TRACE_CUM_ANIMAL_DIR_FWD	INT,
TRACE_CUM_UNIT_IND_FWD		INT,
TRACE_CUM_ANIMAL_IND_FWD	INT,
TRACE_CUM_UNIT_DIR_P_FWD	INT,
TRACE_CUM_ANIMAL_DIR_P_FWD	INT,
TRACE_CUM_UNIT_IND_P_FWD	INT,
TRACE_CUM_ANIMAL_IND_P_FWD	INT,
TRACE_ORIGIN_CUM_UNIT_DIR_FWD	INT,
TRACE_ORIGIN_CUM_UNIT_IND_FWD	INT,
TRACE_ORIGIN_CUM_UNIT_DIR_BACK	INT,
TRACE_ORIGIN_CUM_UNIT_IND_BACK	INT,
TRACE_NEW_UNIT_DIR_FWD		INT,
TRACE_NEW_ANIMAL_DIR_FWD	INT,
TRACE_NEW_UNIT_IND_FWD		INT,
TRACE_NEW_ANIMAL_IND_FWD	INT,
TRACE_CUM_UNIT_DIR_BACK		INT,
TRACE_CUM_ANIMAL_DIR_BACK	INT,
TRACE_CUM_UNIT_IND_BACK		INT,
TRACE_CUM_ANIMAL_IND_BACK	INT,
TRACE_CUM_UNIT_DIR_P_BACK	INT,
TRACE_CUM_ANIMAL_DIR_P_BACK	INT,
TRACE_CUM_UNIT_IND_P_BACK	INT,
TRACE_CUM_ANIMAL_IND_P_BACK	INT,
TRACE_NEW_UNIT_DIR_BACK		INT,
TRACE_NEW_ANIMAL_DIR_BACK	INT,
TRACE_NEW_U_IND_BACK		INT,
TRACE_NEW_ANIMAL_IND_BACK	INT,
TRACE_ORIGIN_NEW_UNIT_DIR_FWD	INT,
TRACE_ORIGIN_NEW_UNIT_IND_FWD	INT,
TRACE_ORIGIN_NEW_UNIT_DIR_BACK	INT,
TRACE_ORIGIN_NEW_UNIT_IND_BACK	INT,
EXAM_CUM_UNIT_DIR_FWD		INT,
EXAM_CUM_ANIMAL_DIR_FWD		INT,
EXAM_CUM_UNIT_IND_FWD		INT,
EXAM_CUM_ANIMAL_IND_FWD		INT,
EXAM_CUM_UNIT_DIR_BACK		INT,
EXAM_CUM_ANIMAL_DIR_BACK	INT,
EXAM_CUM_UNIT_IND_BACK		INT,
EXAM_CUM_ANIMAL_IND_BACK	INT,
EXAM_NEW_UNIT_ALL		INT,
EXAM_NEW_ANIMAL_ALL		INT,
TEST_CUM_UNIT_DIR_FWD		INT,
TEST_CUM_ANIMAL_DIR_FWD		INT,
TEST_CUM_UNIT_IND_FWD		INT,
TEST_CUM_ANIMAL_IND_FWD		INT,
TEST_CUM_UNIT_DIR_BACK		INT,
TEST_CUM_ANIMAL_DIR_BACK	INT,
TEST_CUM_UNIT_IND_BACK		INT,
TEST_CUM_ANIMAL_IND_BACK	INT,
TEST_CUM_UNIT_TRUE_POS		INT,
TEST_CUM_ANIMAL_TRUE_POS	INT,
TEST_NEW_UNIT_TRUE_POS		INT,
TEST_NEW_ANIMAL_TRUE_POS	INT,
TEST_CUM_UNIT_TRUE_NEG		INT,
TEST_CUM_ANIMAL_TRUE_NEG	INT,
TEST_NEW_UNIT_TRUE_NEG		INT,
TEST_NEW_ANIMAL_TRUE_NEG	INT,
TEST_CUM_UNIT_FALSE_POS		INT,
TEST_CUM_ANIMAL_FALSE_POS	INT,
TEST_NEW_UNIT_FALSE_POS		INT,
TEST_NEW_ANIMAL_FALSE_POS	INT,
TEST_CUM_UNIT_FALSE_NEG		INT,
TEST_CUM_ANIMAL_FALSE_NEG	INT,
TEST_NEW_UNIT_FALSE_NEG		INT,
TEST_NEW_ANIMAL_FALSE_NEG	INT,
DETECT_NEW_UNIT_CLIN		INT,
DETECT_NEW_ANIMAL_CLIN		INT,
DETECT_CUM_UNIT_CLIN		INT,
DETECT_CUM_ANIMAL_CLIN		INT,
DETECT_NEW_UNIT_TEST		INT,
DETECT_NEW_ANIMAL_TEST		INT,
DETECT_CUM_UNIT_TEST		INT,
DETECT_CUM_ANIMAL_TEST		INT,
DESTROY_CUM_UNIT_INITIAL	INT,
DESTROY_CUM_ANIMAL_INITIAL	INT,
DESTROY_CUM_UNIT_DETECT		INT,
DESTROY_CUM_ANIMAL_DETECT	INT,
DESTROY_CUM_UNIT_DIR_FWD	INT,
DESTROY_CUM_ANIMAL_DIR_FWD	INT,
DESTROY_CUM_UNIT_IND_FWD	INT,
DESTROY_CUM_ANIMAL_IND_FWD	INT,
DESTROY_CUM_UNIT_DIR_BACK	INT,
DESTROY_CUM_ANIMAL_DIR_BACK	INT,
DESTROY_CUM_UNIT_IND_BACK	INT,
DESTROY_CUM_ANIMAL_IND_BACK	INT,
DESTROY_CUM_UNIT_RING		INT,
DESTROY_CUM_ANIMAL_RING		INT,
DESTROY_NEW_UNIT_ALL		INT,
DESTROY_NEW_ANIMAL_ALL		INT,
DESTROY_WAIT_UNIT_ALL		INT,
DESTROY_WAIT_ANIMAL_ALL		INT,
VAC_CUM_UNIT_INITIAL		INT,
VAC_CUM_ANIMAL_INITIAL		INT,
VAC_CUM_UNIT_RING		INT,
VAC_CUM_ANIMAL_RING		INT,
VAC_NEW_UNIT_ALL		INT,
VAC_NEW_ANIMAL_ALL		INT,
VAC_WAIT_UNIT_ALL		INT,
VAC_WAIT_ANIMAL_ALL		INT,
ZONE_NEW_FOCI			INT,
ZONE_CUM_FOCI			INT
);

CREATE TABLE OUTDAILYBYZONE (
ITERATION	INT,
DAY		INT,
ZONE_ID		INT,
ZONE_AREA	REAL,
ZONE_PERIMETER	REAL
);

CREATE TABLE OUTDAILYBYZONEANDPRODUCTIONTYPE  (
ITERATION		INT,
DAY			INT,
ZONE_ID			INT,
PRODUCTION_TYPE_ID	INT,
UNIT_DAYS_IN_ZONE	INT,
ANIMAL_DAYS_IN_ZONE	INT,
UNITS_IN_ZONE		INT,
ANIMALS_IN_ZONE		INT
);

CREATE TABLE OUTDAILYEVENTS (

ITERATION	INT,
DAY		INT,
EVENT		INT,
HERD_ID		INT,
ZONE_ID		INT,  -- I think this should be zone description
EVENT_CODE	TEXT, -- I think this should be event description
NEW_STATE_CODE	TEXT, -- I think this should be state description
TEST_RESULT_CODE	TEXT  
);

CREATE TABLE OUTDAILYEXPOSURES (
ITERATION		INT,
DAY			INT,
EXPOSURE		INT,
INITIATED_DAY		INT,
EXPOSED_HERD_ID		INT,
EXPOSED_ZONE_ID		INT,
EXPOSING_HERD_ID	INT,
EXPOSING_ZONE_ID	INT,
SPREAD_METHOD_CODE	TEXT,
IS_ADEQUATE		INT,
EXPOSING_HERD_STATUS_CODE	TEXT,
EXPOSED_HERD_STATUS_CODE	TEXT
);

CREATE TABLE OUTEPIDEMICCURVES (
ITERATION			INT,
DAY				INT,
PRODUCTION_TYPE_ID		INT,
INFECTED_UNITS			INT,
INFECTED_ANIMALS		INT,
DETECTED_UNITS			INT,
DETECTED_ANIMALS		INT,
INFECTIOUS_UNITS		INT,
APPARENT_INFECTIOUS_UNITS	INT
);

CREATE TABLE OUTGENERAL (
OUT_GENERAL_ID		TEXT, -- yuck is this that versionapplication thing
SIMULATION_START_TIME	TEXT,
SIMULATION_END_TIME	TEXT,  -- really, why don't we just calculate a run time, isn't that what shows up?
COMPLETED_ITERATIONS	INT,
VERSION			TEXT
);

CREATE TABLE OUTITERATION (
ITERATION		INT,
DISEASE_ENDED		INT,
DISEASE_END_DAY		INT,
OUTBREAK_ENDED		INT,
OUTBREAK_END_DAY	INT,
ZONE_FOCI_CREATED	INT,
DESTROY_WAIT_UNIT_MAX	INT,
DESTROY_WAIT_UNIT_MAX_DAY	INT,
DESTROY_WAIT_ANIMAL_MAX		REAL,
DESTROY_WAIT_ANIMAL_MAX_DAY	INT,
DESTROY_WAIT_UNIT_TIME_MAX	INT,
DESTROY_WAIT_UNIT_TIME_AVG	REAL,
VAC_WAIT_UNIT_MAX		INT,
VAC_WAIT_UNIT_MAX_DAY	INT,
VAC_WAIT_ANIMAL_MAX	REAL,
VAC_WAIT_ANIMAL_MAX_DAY	INT,
VAC_WAIT_UNIT_TIME_MAX	INT,
VAC_WAIT_UNIT_TIME_AVG	REAL
);


CREATE TABLE OUTITERATIONBYHERD (
ITERATION		INT,
HERD_ID			INT,
LAST_STATUS_CODE	TEXT,  -- why not put the descriptions in here instead since we are writing it?
LAST_STATUS_DAY		INT,
LAST_CONTROL_STATE_CODE	TEXT,	-- why not put the descriptions in here since we are writing it?
LAST_CONTROL_STATE_DAY	INT
);



CREATE TABLE OUTITERATIONBYPRODUCTIONTYPE (

ITERATION		INT,
PRODUCTION_TYPE_ID	INT,
TRANSITION_STATE_CUM_UNIT_SUSCEPTIBLE	INT,
TRANSITION_STATE_CUM_ANIMAL_SUSCEPTIBLE	INT,
TRANSITION_STATE_CUM_UNIT_LATENT	INT,
TRANSITION_STATE_CUM_ANIMAL_LATENT	INT,
TRANSITION_STATE_CUM_UNIT_SUBCLINICAL	INT,
TRANSITION_STATE_CUM_ANIMAL_SUBCLINICAL	INT,
TRANSITION_STATE_CUM_UNIT_CLINICAL	INT,
TRANSITION_STATE_CUM_ANIMAL_CLINICAL	INT,
TRANSITION_STATE_CUM_UNIT_NAT_IMMUNE	INT,
TRANSITION_STATE_CUM_ANIMAL_NAT_IMMUNE	INT,
TRANSITION_STATE_CUM_UNIT_VAC_IMMUNE	INT,
TRANSITION_STATE_CUM_ANIMAL_VAC_IMMUNE	INT,
TRANSITION_STATE_CUM_UNIT_DESTROYED	INT,
TRANSITION_STATE_CUM_ANIMAL_DESTROYED	INT,
INFECTION_CUM_UNIT_INITIAL		INT,
INFECTION_CUM_ANIMAL_INITIAL	INT,
INFECTION_CUM_UNIT_AIR		INT,
INFECTION_CUM_ANIMAL_AIR	INT,
INFECTION_CUM_UNIT_DIR		INT,
INFECTION_CUM_ANIMAL_DIR	INT,
INFECTION_CUM_UNIT_IND		INT,
INFECTION_CUM_ANIMAL_IND	INT,
EXPOSED_CUM_UNIT_DIR		INT,
EXPOSED_CUM_ANIMAL_DIR		INT,
EXPOSED_CUM_UNIT_IND		INT,
EXPOSED_CUM_ANIMAL_IND		INT,
TRACE_CUM_UNIT_DIR_FWD		INT,
TRACE_CUM_ANIMAL_DIR_FWD	INT,
TRACE_CUM_UNIT_IND_FWD		INT,
TRACE_CUM_ANIMAL_IND_FWD	INT,
TRACE_CUM_UNIT_DIR_P_FWD	INT,
TRACE_CUM_ANIMAL_DIR_PFWD	INT,
TRACE_CUM_UNIT_IND_P_FWD	INT,
TRACE_CUM_ANIMAL_IND_P_FWD	INT,
TRACE_CUM_UNIT_DIR_BACK		INT,
TRACE_CUM_ANIMAL_DIR_BACK	INT,
TRACE_CUM_UNIT_IND_BACK		INT,
TRACE_CUM_ANIMAL_IND_BACK	INT,
TRACE_CUM_UNIT_DIR_P_BACK	INT,
TRACE_CUM_ANIMAL_DIR_PBACK	INT,
TRACE_CUM_UNIT_IND_P_BACK	INT,
TRACE_CUM_ANIMAL_IND_P_BACK	INT,
TRACE_ORIGIN_CUM_UNIT_DIR_FWD	INT,
TRACE_ORIGIN_CUM_UNIT_IND_FWD	INT,
TRACE_ORIGIN_CUM_UNIT_DIR_BACK	INT,
TRACE_ORIGIN_CUM_UNIT_IND_BACK	INT,
EXAM_CUM_UNIT_DIR_FWD		INT,
EXAM_CUM_ANIMAL_DIR_FWD		INT,
EXAM_CUM_UNIT_IND_FWD		INT,
EXAM_CUM_ANIMAL_IND_FWD		INT,
EXAM_CUM_UNIT_DIR_BACK		INT,
EXAM_CUM_ANIMAL_DIR_BACK	INT,
EXAM_CUM_UNIT_IND_BACK		INT,
EXAM_CUM_ANIMAL_IND_BACK	INT,
TEST_CUM_UNIT_DIR_FWD		INT,
TEST_CUM_ANIMAL_DIR_FWD		INT,
TEST_CUM_UNIT_IND_FWD		INT,
TEST_CUM_ANIMAL_IND_FWD		INT,
TEST_CUM_UNIT_DIR_BACK		INT,
TEST_CUM_ANIMAL_DIR_BACK	INT,
TEST_CUM_UNIT_IND_BACK		INT,
TEST_CUM_ANIMAL_IND_BACK	INT,
TEST_CUM_UNIT_TRUE_POS		INT,
TEST_CUM_ANIMAL_TRUE_POS	INT,
TEST_CUM_UNIT_TRUE_NEG		INT,
TEST_CUM_ANIMAL_TRUE_NEG	INT,
TEST_CUM_UNIT_FALSE_POS		INT,
TEST_CUM_ANIMAL_FALSE_POS	INT,
TEST_CUM_UNIT_FALSE_NEG		INT,
TEST_CUM_ANIMAL_FALSE_NEG	INT,
DETECT_CUM_UNIT_CLIN		INT,
DETECT_CUM_ANIMAL_CLIN		INT,
DETECT_CUM_UNIT_TEST		INT,
DETECT_CUM_ANIMAL_TEST		INT,
DESTROY_CUM_UNIT_INITIAL	INT,
DESTROY_CUM_ANIMAL_INITIAL	INT,
DESTROY_CUM_UNIT_DETECT		INT,
DESTROY_CUM_ANIMAL_DETECT	INT,
DESTROY_CUM_UNIT_DIR_FWD	INT,
DESTROY_CUM_ANIMAL_DIR_FWD	INT,
DESTROY_CUM_UNIT_IND_FWD	INT,
DESTROY_CUM_ANIMAL_IND_FWD	INT,
DESTROY_CUM_UNIT_DIR_BACK	INT,
DESTROY_CUM_ANIMAL_DIR_BACK	INT,
DESTROY_CUM_UNIT_IND_BACK	INT,
DESTROY_CUM_ANIMAL_IND_BACK	INT,
DESTROY_CUM_UNIT_RING		INT,
DESTROY_CUM_ANIMAL_RING		INT,
DESTROY_WAIT_UNIT_MAX		INT,
DESTROY_WAIT_ANIMAL_MAX		REAL
DESTROY_WAIT_UNIT_MAX_DAY	INT,
DESTROY_WAIT_ANIMAL_MAX_DAY	INT,
DESTROY_WAIT_UNIT_TIME_MAX	INT,
DESTROY_WAIT_UNIT_TIME_AVG	REAL
DESTROY_WAIT_UNIT_DAYS_IN_QUEUE	REAL
DESTROY_WAIT_ANIMAL_DAYS_IN_QUEUE	REAL
VAC_CUM_UNIT_INITIAL		INT,
VAC_CUM_ANIMAL_INITIAL		INT,
VAC_CUM_UNIT_RING		INT,
VAC_CUM_ANIMAL_RING		INT, --
VAC_WAIT_UNIT_MAX		INT,
VAC_WAIT_ANIMAL_MAX		REAL  -- 
VAC_WAIT_UNIT_MAX_DAY		INT,
VAC_WAIT_ANIMAL_MAX_DAY		INT,
VAC_WAIT_UNIT_TIME_MAX		REAL
VAC_WAIT_UNIT_TIME_AVG		INT,
ZONC_FOCI			INT,
FIRST_DETECTION			INT,
FIRST_DET_UNIT_INF		INT,
FIRST_DETECT_ANIMAL_INF		INT,
FIRST_DESTRUCTION		INT,
FIRST_VACCINATION		INT,
LAST_DETECTION			INT
);

CREATE TABLE OUTITERATIONBYZONE (
ITERATION		INT,
ZONE_ID			INT,
MAX_ZONE_AREA		REAL,
MAX_ZONE_AREA_DAY	INT,
FINAL_ZONE_AREA		REAL,
MAX_ZONE_PERIMETER	REAL,
MAX_ZONE_PERIMETER_DAY	INT,
FINAL_ZONE_PERIMETER	REAL
);

CREATE TABLE OUTITERATIONBYZONEANDPRODUCTIONTYPE (
ITERATION		INT,
ZONE_ID			INT,
PRODUCTION_TYPE_ID	INT,
UNIT_DAYS_IN_ZONE	INT,
ANIMAL_DAYS_IN_ZONE	INT,
COST_SURVEILLANCE	REAL
);

CREATE TABLE OUTITERATIONCOSTS (
ITERATION		INT,
PRODUCTION_TYPE_ID	INT,
DESTROY_APPRAISAL	REAL,
DESTROY_CLEANING	REAL,
DESTROY_EUTHANASIA	REAL,
DESTROY_INDEMNIFICATION	REAL,
DESTROY_DISPOSAL	REAL,
VAC_CUM_SETUP		REAL,
VAC_CUM_VACCINATION	REAL
);






